### ISSUE TITLE
1, 2 question about

### ISSUE THREAD

**Issue by serkandyck** [JohnTendik/LazyGo#1]
Hello dude, i need help if device set Mock location Pokemon Go client detected and getting error. your phone rooted ?

**Comment by JohnTendik** [comment]
Yes you need a rooted phone for mock locations to work otherwise the game can detect it and won't work.

On Jul 17, 2016 11:56 AM, Serkan Dayıcık notifications@github.com wrote:

Hello dude, i need help if device set Mock location Pokemon Go client detected and getting error. your phone rooted ?
